#!/bin/env bash

tar zxvf /data/EHC_Final.tar.gz
hadoop fs -mkdir hdfs://master/tmp/Team34
hadoop fs -put EHC/EHC_2nd_round_train.log hdfs://master/tmp/Team34/EHC_2nd_round_train.log
hadoop fs -put EHC/EHC_2nd_round_test.log hdfs://master/tmp/Team34/EHC_2nd_round_test.log

# 比賽時會在解開的目錄內執行
workspace=`pwd`/EHC/
export JAVA_OPTS="-Dfile.encoding=utf-8 -DEHC_FINAL_DATASET_DIR=$workspace"
CMD=bin/preprocessing

$CMD user EHC_2nd_round_train.log userdata_train.csv
$CMD user EHC_2nd_round_test.log userdata_test.csv
$CMD product EHC_2nd_round_train.log product_train.csv
$CMD product EHC_2nd_round_test.log product_test.csv

Rscript generate_user_model.r $workspace userdata_train.csv userdata_test.csv userdata_predict.csv
Rscript generate_product_model.r $workspace product_train.csv product_test.csv product_predict.csv
$CMD result6 EHC_2nd_round_test.log userdata_predict.csv product_predict.csv 3 result.txt 
